FROM python:3.8-slim

ARG DRONE_COMMIT_SHA DRONE_BUILD_NUMBER DRONE_BUILD_LINK DRONE_COMMIT_LINK DRONE_REPO_LINK DRONE_BUILD_FINISHED
ENV DRONE_COMMIT_SHA=$DRONE_COMMIT_SHA DRONE_BUILD_NUMBER=$DRONE_BUILD_NUMBER DRONE_BUILD_LINK=$DRONE_BUILD_LINK DRONE_COMMIT_LINK=$DRONE_COMMIT_LINK DRONE_REPO_LINK=$DRONE_REPO_LINK DRONE_BUILD_FINISHED=$DRONE_BUILD_FINISHED

ENV MATOMO_SITE_ID MATOMO_URL TARGET_ENV ONION_ADDRESS
ENV APP_DIR=/usr/src/snappass

RUN groupadd -r snappass && \
    useradd -r -g snappass snappass && \
    mkdir -p $APP_DIR

WORKDIR $APP_DIR

COPY ["setup.py", "MANIFEST.in", "README.rst", "AUTHORS.rst", "$APP_DIR/"]
COPY ["./snappass", "$APP_DIR/snappass"]

RUN python setup.py install && \
    chown -R snappass $APP_DIR && \
    chgrp -R snappass $APP_DIR

USER snappass

# Default Flask port
EXPOSE 5000

CMD ["snappass"]
